baseURL              = "https://emerson-silva.blog.br"
publishDir           = "public"          # pode remover se deixar default
defaultContentLanguage = "pt-br"
languageCode         = "pt-br"
title                = "Emerson Silva"
theme                = "LoveIt"

###############################################################################
# Params padrão do LoveIt
###############################################################################
[params]
  version = "0.3.0"     # permanece aqui
  defaultTheme = "dark"

  [params.author]
    name = "Emerson Silva"
    link = "https://emerson-silva.blog.br"


  ###########################################################################
  # Comentários – Giscus
  ###########################################################################
  [params.comment]
    enable = true

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      name = "Emerson Siva"
      typeit = false


    [params.comment.giscus]
      enable          = true
      repo            = "silvemerson/emerson-silva-blog"
      repoId          = "R_kgDONTalJA"
      category        = "General"
      categoryId      = "DIC_kwDONTalJM4CkhmM"
      mapping         = "pathname"
      reactionsEnabled = true
      emitMetadata    = true
      inputPosition   = "top"
      theme           = "dark"
      lang            = "pt"
      lazyLoading     = true

  ###########################################################################
  # Home
  ###########################################################################
  [params.home]
    rss = 10

    [params.home.profile]
      enable      = true
      avatarURL   = "https://avatars.githubusercontent.com/u/39895958?v=4"
      title       = "Emerson Silva"
      subtitle    = "Aqui o assunto é sobre DevOps e um pouco mais!"
      typeit      = true
      social      = true
      disclaimer  = ""

    [params.home.posts]
      enable      = true
      paginate    = 20
      defaultHiddenFromHomePage = false

  ###########################################################################
  # Redes sociais
  ###########################################################################
  [params.social]
    github        = "silvemerson"
    linkedin      = "silvemerson"
    instagram     = "silvemerson_"
    youtube       = "UCvHjFEBsZF3iom8hHOQwpGA"
    telegram      = "silvemerson"


  [params.analytics]
    enable = true   
    [params.analytics.google]
      id = "G-B7YRXX3Q8D"
      respectDoNotTrack = true
###############################################################################
# Menu principal
###############################################################################
[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
    weight     = 1

  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags/"
    weight     = 2

  [[menu.main]]
    identifier = "categories"
    name       = "Categories"
    url        = "/categories/"
    weight     = 3

###############################################################################
# Markup / Highlight
###############################################################################
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
