---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker-ubuntu1804-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
